contact_form/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.contact, name='index'),
    path('thanks/', views.thanks, name='thanks'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from contact_form import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', include(('contact_form.urls', 'contact_form'), namespace='contact_form')),
    path('admin/', admin.site.urls),
]

contact_form/models.py
from django.db import models


class ContactFormSubmission(models.Model):
    SUBJECT_CHOICES = [
        ('Account',) * 2,
        ('Payment',) * 2,
        ('General feedback',) * 2,
        ('Other',) * 2,
    ]

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, blank=True, default='')
    email = models.EmailField()
    subject = models.CharField(max_length=200, choices=SUBJECT_CHOICES)
    message = models.CharField(max_length=3000)

contact_form/forms.py
from django.forms import ModelForm, Textarea, Select

from contact_form.models import ContactFormSubmission

_subject_choices = (
    'Account',
    'Payment',
    'General feedback',
    'Other',
)


class ContactForm(ModelForm):
    class Meta:
        model = ContactFormSubmission
        fields = '__all__'
        widgets = {
            'subject': Select(choices=((c, c) for c in _subject_choices)),
            'message': Textarea(),
        }

contact_form/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from contact_form.forms import ContactForm


def index(request):
    return render(request, 'index.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('contact_form:thanks'))
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})


def thanks(request):
    return render(request, 'thanks.html')

contact_form/templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style type="text/css">
        main > .container {
            padding-top: 56px;
        }
        .form-container {
            max-width: 800px;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <title>{% block title %}Django contact form{% endblock %}</title>
</head>
<body class="d-flex flex-column h-100">
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/contact/">Django contact form</a>
        </div>
    </nav>
</header>
<main role="main" class="flex-shrink-0">
    {% block body %}{% endblock %}
</main>
<footer class="footer mt-auto py-3" style="background: #f5f5f5">
    <div class="container">
        <span class="text-muted">© Copyright 2020 Sumit Chahal</span>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

contact_form/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="form-container">
            <h1 class="mt-5">Contact us</h1>
            <form action="{% url 'contact_form:index' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                {{ form.email|as_crispy_field }}
                {{ form.subject|as_crispy_field }}
                {{ form.message|as_crispy_field }}

                <button type="submit" class="btn btn-success">Submit</button>

{#                <div class="row">#}
{#                    <div class="col-md-6 mb-3">#}
{#                        {{ form.first_name|as_crispy_field }}#}
{#                    </div>#}
{#                </div>#}
{#                {% crispy form %}#}
{#                {{ form }}#}
{#                {{ form.non_field_errors }}#}
{#                <div class="row">#}
{#                    <div class="col-md-6 mb-3">#}
{#                        <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>#}
{#                        {{ form.first_name.errors }}#}
{#                        <input type="text" class="form-control" id="{{ form.first_name.id_for_label }}" maxlength="{{ form.first_name.max_length }}" required>#}
{#                    </div>#}
{#                    <div class="col-md-6 mb-3">#}
{#                        <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>#}
{#                        {{ form.last_name.errors }}#}
{#                        <input type="text" class="form-control" id="{{ form.last_name.id_for_label }}" required>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="form-group">#}
{#                    <input type="submit" value="Submit" class="btn btn-primary" />#}
{#                </div>#}
            </form>
        </div>
    </div>
{% endblock %}

contact_form/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="form-container">
            <h1 class="mt-5">Welcome</h1>
            <p>Wow, such empty. Try the <a href="{% url 'contact_form:index' %}">contact page</a>, maybe?</p>
        </div>
    </div>
{% endblock %}

contact_form/templates/thanks.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="form-container">
            <h1 class="mt-5">Thanks!</h1>
            <p>Thanks for contacting us! We will get back to you shortly.</p>
            <a class="btn btn-primary" href="{% url 'index' %}">Go home</a>
        </div>
    </div>
{% endblock %}